import 'package:flutter/material.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedriwayatdeteksiwidget1/generated/GeneratedFrame14Widget1.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedriwayatdeteksiwidget1/generated/GeneratedRiwayatDeteksiWidget2.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedriwayatdeteksiwidget1/generated/GeneratedGroup26Widget5.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedriwayatdeteksiwidget1/generated/GeneratedRectangle1Widget14.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedriwayatdeteksiwidget1/generated/GeneratedFrame12Widget1.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedriwayatdeteksiwidget1/generated/GeneratedFrame11Widget1.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedriwayatdeteksiwidget1/generated/GeneratedFrame13Widget1.dart';

/* Frame Riwayat Deteksi
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRiwayatDeteksiWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 812.0,
                child: GeneratedRectangle1Widget14(),
              ),
              Positioned(
                left: 35.0,
                top: 704.0,
                right: null,
                bottom: null,
                width: 305.0,
                height: 66.0,
                child: GeneratedGroup26Widget5(),
              ),
              Positioned(
                left: 40.0,
                top: 60.0,
                right: null,
                bottom: null,
                width: 298.0,
                height: 30.0,
                child: GeneratedRiwayatDeteksiWidget2(),
              ),
              Positioned(
                left: 35.0,
                top: 131.0,
                right: null,
                bottom: null,
                width: 305.0,
                height: 85.0,
                child: GeneratedFrame11Widget1(),
              ),
              Positioned(
                left: 35.0,
                top: 243.0,
                right: null,
                bottom: null,
                width: 305.0,
                height: 85.0,
                child: GeneratedFrame12Widget1(),
              ),
              Positioned(
                left: 35.0,
                top: 355.0,
                right: null,
                bottom: null,
                width: 305.0,
                height: 85.0,
                child: GeneratedFrame13Widget1(),
              ),
              Positioned(
                left: 35.0,
                top: 467.0,
                right: null,
                bottom: null,
                width: 305.0,
                height: 85.0,
                child: GeneratedFrame14Widget1(),
              )
            ]),
      ),
    ));
  }
}
