import 'package:flutter/material.dart';

/* Rectangle image 4
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedImage4Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 1025.0,
      height: 735.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Image.asset(
          "assets/images/bfcbd168263f6fbab4d501015c8279719391906b.png",
          color: null,
          fit: BoxFit.cover,
          width: 1025.0,
          height: 735.0,
          colorBlendMode: BlendMode.dstATop,
        ),
      ),
    ));
  }
}
