import 'package:flutter/material.dart';

/* Rectangle image 2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedImage2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 676.0,
      height: 505.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Image.asset(
          "assets/images/85802e5785014db2f552ff1e78ddbf4fe647edf3.png",
          color: null,
          fit: BoxFit.cover,
          width: 676.0,
          height: 505.0,
          colorBlendMode: BlendMode.dstATop,
        ),
      ),
    ));
  }
}
