import 'package:flutter/material.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedregisterwidget/generated/GeneratedGroup1Widget2.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedregisterwidget/generated/GeneratedLine2Widget1.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedregisterwidget/generated/GeneratedGroup12Widget.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedregisterwidget/generated/GeneratedExam1Widget.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedregisterwidget/generated/GeneratedNamalengkapWidget.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedregisterwidget/generated/GeneratedGroup10Widget.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedregisterwidget/generated/GeneratedDaftarWidget1.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedregisterwidget/generated/GeneratedGroup9Widget.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedregisterwidget/generated/GeneratedRectangle1Widget18.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedregisterwidget/generated/GeneratedIconparkoutlinepeopleWidget.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedregisterwidget/generated/GeneratedBxsmusicWidget9.dart';

/* Frame Register
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRegisterWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 812.0,
                child: GeneratedRectangle1Widget18(),
              ),
              Positioned(
                left: 318.0,
                top: 259.0,
                right: null,
                bottom: null,
                width: 12.0,
                height: 12.0,
                child: GeneratedBxsmusicWidget9(),
              ),
              Positioned(
                left: 33.0,
                top: 372.0,
                right: null,
                bottom: null,
                width: 310.0,
                height: 51.0,
                child: GeneratedDaftarWidget1(),
              ),
              Positioned(
                left: 33.0,
                top: 434.0,
                right: null,
                bottom: null,
                width: 307.0,
                height: 24.0,
                child: GeneratedGroup10Widget(),
              ),
              Positioned(
                left: 79.0,
                top: 490.0,
                right: null,
                bottom: null,
                width: 128.0,
                height: 20.0,
                child: GeneratedNamalengkapWidget(),
              ),
              Positioned(
                left: 78.0,
                top: 512.0,
                right: null,
                bottom: null,
                width: 262.0,
                height: 0.5,
                child: GeneratedLine2Widget1(),
              ),
              Positioned(
                left: 35.0,
                top: 489.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedIconparkoutlinepeopleWidget(),
              ),
              Positioned(
                left: 37.0,
                top: 546.0,
                right: null,
                bottom: null,
                width: 303.0,
                height: 22.0,
                child: GeneratedGroup12Widget(),
              ),
              Positioned(
                left: 34.0,
                top: 597.0,
                right: null,
                bottom: null,
                width: 308.0,
                height: 35.0,
                child: GeneratedGroup9Widget(),
              ),
              Positioned(
                left: 35.0,
                top: 656.0,
                right: null,
                bottom: null,
                width: 305.0,
                height: 35.0,
                child: GeneratedGroup1Widget2(),
              ),
              Positioned(
                left: -24.0,
                top: 49.0,
                right: null,
                bottom: null,
                width: 424.0,
                height: 319.0,
                child: GeneratedExam1Widget(),
              )
            ]),
      ),
    ));
  }
}
