import 'package:flutter/material.dart';

/* Rectangle image 5
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedImage5Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 695.0,
      height: 735.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Image.asset(
          "assets/images/7371a11ba4f86275647d8b12a4236925babb77b8.png",
          color: null,
          fit: BoxFit.cover,
          width: 695.0,
          height: 735.0,
          colorBlendMode: BlendMode.dstATop,
        ),
      ),
    ));
  }
}
