import 'package:flutter/material.dart';

/* Rectangle image 6
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedImage6Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 1062.0,
      height: 693.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Image.asset(
          "assets/images/e32197f75a09e828aee8d84e640cae1ca0077a3e.png",
          color: null,
          fit: BoxFit.cover,
          width: 1062.0,
          height: 693.0,
          colorBlendMode: BlendMode.dstATop,
        ),
      ),
    ));
  }
}
