import 'package:flutter/material.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedartistpagewidget/generated/GeneratedFrame21Widget.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedartistpagewidget/generated/GeneratedFrame9Widget1.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedartistpagewidget/generated/GeneratedEvaarrowiosbackoutlineWidget5.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedartistpagewidget/generated/GeneratedRectangle1Widget9.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedartistpagewidget/generated/GeneratedFrame18Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedartistpagewidget/generated/GeneratedFrame7Widget.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedartistpagewidget/generated/GeneratedFrame19Widget.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedartistpagewidget/generated/GeneratedBxsmusicWidget8.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedartistpagewidget/generated/GeneratedLilUziVertWidget2.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedartistpagewidget/generated/GeneratedImage17Widget.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedartistpagewidget/generated/GeneratedFrame10Widget1.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedartistpagewidget/generated/GeneratedFrame20Widget.dart';

/* Frame Artist Page
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedArtistPageWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              return SingleChildScrollView(
                scrollDirection: Axis.vertical,
                child: Container(
                    height: 1076.0,
                    child: Stack(children: [
                      Container(
                          width: constraints.maxWidth,
                          child: Container(
                            width: 375.0,
                            height: 1076.0,
                            child: Stack(
                                fit: StackFit.expand,
                                alignment: Alignment.center,
                                overflow: Overflow.visible,
                                children: [
                                  ClipRRect(
                                    borderRadius: BorderRadius.zero,
                                    child: Container(
                                      color: Color.fromARGB(255, 255, 255, 255),
                                    ),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 0.0,
                                    right: null,
                                    bottom: null,
                                    width: 375.0,
                                    height: 812.0,
                                    child: GeneratedRectangle1Widget9(),
                                  ),
                                  Positioned(
                                    left: 318.0,
                                    top: 259.0,
                                    right: null,
                                    bottom: null,
                                    width: 12.0,
                                    height: 12.0,
                                    child: GeneratedBxsmusicWidget8(),
                                  ),
                                  Positioned(
                                    left: -5.0,
                                    top: -45.0,
                                    right: null,
                                    bottom: null,
                                    width: 380.0,
                                    height: 349.0,
                                    child: GeneratedImage17Widget(),
                                  ),
                                  Positioned(
                                    left: 35.0,
                                    top: 195.0,
                                    right: null,
                                    bottom: null,
                                    width: 250.0,
                                    height: 42.0,
                                    child: GeneratedLilUziVertWidget2(),
                                  ),
                                  Positioned(
                                    left: 35.0,
                                    top: 332.0,
                                    right: null,
                                    bottom: null,
                                    width: 310.0,
                                    height: 28.0,
                                    child: GeneratedFrame7Widget(),
                                  ),
                                  Positioned(
                                    left: 35.0,
                                    top: 692.0,
                                    right: null,
                                    bottom: null,
                                    width: 310.0,
                                    height: 28.0,
                                    child: GeneratedFrame20Widget(),
                                  ),
                                  Positioned(
                                    left: 35.0,
                                    top: 371.0,
                                    right: null,
                                    bottom: null,
                                    width: 305.0,
                                    height: 85.0,
                                    child: GeneratedFrame9Widget1(),
                                  ),
                                  Positioned(
                                    left: 35.0,
                                    top: 472.0,
                                    right: null,
                                    bottom: null,
                                    width: 305.0,
                                    height: 85.0,
                                    child: GeneratedFrame10Widget1(),
                                  ),
                                  Positioned(
                                    left: 35.0,
                                    top: 573.0,
                                    right: null,
                                    bottom: null,
                                    width: 305.0,
                                    height: 85.0,
                                    child: GeneratedFrame19Widget(),
                                  ),
                                  Positioned(
                                    left: 35.0,
                                    top: 733.0,
                                    right: null,
                                    bottom: null,
                                    width: 340.0,
                                    height: 157.0,
                                    child: GeneratedFrame21Widget(),
                                  ),
                                  Positioned(
                                    left: null,
                                    top: 60.0,
                                    right: null,
                                    bottom: null,
                                    width: 27.0,
                                    height: 27.0,
                                    child: TransformHelper.translate(
                                        x: -146.00,
                                        y: 0.00,
                                        z: 0,
                                        child:
                                            GeneratedEvaarrowiosbackoutlineWidget5()),
                                  )
                                ]),
                          ))
                    ])),
              );
            }),
            Positioned(
              left: null,
              top: null,
              right: null,
              bottom: 28.0,
              width: 305.0,
              height: 66.0,
              child: GeneratedFrame18Widget(),
            )
          ]),
    ));
  }
}
