import 'package:flutter/material.dart';

/* Frame fluent:sound-wave-circle-24-filled
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFluentsoundwavecircle24filledWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 24.0,
        height: 24.0,
      ),
    ));
  }
}
