import 'package:flutter/material.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedpasswordwidget1/generated/GeneratedAkariconseyeslashedWidget2.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedpasswordwidget1/generated/GeneratedBxsmusicWidget10.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedpasswordwidget1/generated/GeneratedGroup14Widget.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedpasswordwidget1/generated/GeneratedSandiWidget.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedpasswordwidget1/generated/GeneratedEvaarrowiosbackoutlineWidget14.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedpasswordwidget1/generated/GeneratedAkariconseyeslashedWidget1.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedpasswordwidget1/generated/GeneratedPasswordreset1Widget.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedpasswordwidget1/generated/GeneratedGroup1Widget3.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedpasswordwidget1/generated/GeneratedRectangle1Widget20.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedpasswordwidget1/generated/GeneratedGroup13Widget.dart';

/* Frame Password
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPasswordWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 812.0,
                child: GeneratedRectangle1Widget20(),
              ),
              Positioned(
                left: 318.0,
                top: 337.0,
                right: null,
                bottom: null,
                width: 12.0,
                height: 12.0,
                child: GeneratedBxsmusicWidget10(),
              ),
              Positioned(
                left: 33.0,
                top: 450.0,
                right: null,
                bottom: null,
                width: 310.0,
                height: 51.0,
                child: GeneratedSandiWidget(),
              ),
              Positioned(
                left: 35.0,
                top: 627.0,
                right: null,
                bottom: null,
                width: 305.0,
                height: 35.0,
                child: GeneratedGroup1Widget3(),
              ),
              Positioned(
                left: 35.0,
                top: 509.0,
                right: null,
                bottom: null,
                width: 305.0,
                height: 25.0,
                child: GeneratedGroup13Widget(),
              ),
              Positioned(
                left: 35.0,
                top: 565.0,
                right: null,
                bottom: null,
                width: 305.0,
                height: 25.0,
                child: GeneratedGroup14Widget(),
              ),
              Positioned(
                left: -31.0,
                top: 118.0,
                right: null,
                bottom: null,
                width: 428.0,
                height: 320.0,
                child: GeneratedPasswordreset1Widget(),
              ),
              Positioned(
                left: 317.0,
                top: 508.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedAkariconseyeslashedWidget1(),
              ),
              Positioned(
                left: 317.0,
                top: 562.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedAkariconseyeslashedWidget2(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.072;

                  final double height =
                      constraints.maxHeight * 0.0332512315270936;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.07733333333333334,
                        y: constraints.maxHeight * 0.07266009852216748,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedEvaarrowiosbackoutlineWidget14(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
