import 'package:flutter/material.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedhiphoppopularpagewidget/generated/GeneratedEvaarrowiosbackoutlineWidget4.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedhiphoppopularpagewidget/generated/GeneratedFrame11Widget.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedhiphoppopularpagewidget/generated/GeneratedFrame9Widget.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedhiphoppopularpagewidget/generated/GeneratedFrame16Widget.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedhiphoppopularpagewidget/generated/GeneratedFrame13Widget.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedhiphoppopularpagewidget/generated/GeneratedWantItAllfeWidget.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedhiphoppopularpagewidget/generated/GeneratedImage10Widget.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedhiphoppopularpagewidget/generated/GeneratedUnsplash0EEKgGOe3psWidget1.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedhiphoppopularpagewidget/generated/GeneratedFrame10Widget.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedhiphoppopularpagewidget/generated/GeneratedFrame15Widget.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedhiphoppopularpagewidget/generated/GeneratedRectangle1Widget8.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedhiphoppopularpagewidget/generated/GeneratedRectangle12Widget.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedhiphoppopularpagewidget/generated/GeneratedBurnaBoyWidget.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedhiphoppopularpagewidget/generated/GeneratedBxsmusicWidget7.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedhiphoppopularpagewidget/generated/GeneratedHiphopPopulerWidget1.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedhiphoppopularpagewidget/generated/GeneratedFrame14Widget.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedhiphoppopularpagewidget/generated/GeneratedUnsplash0EEKgGOe3psWidget.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedhiphoppopularpagewidget/generated/GeneratedHiphopPopulerWidget2.dart';

/* Frame Hiphop Popular Page
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHiphopPopularPageWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              return SingleChildScrollView(
                scrollDirection: Axis.vertical,
                child: Container(
                    height: 1076.0,
                    child: Stack(children: [
                      Container(
                          width: constraints.maxWidth,
                          child: Container(
                            width: 375.0,
                            height: 1076.0,
                            child: Stack(
                                fit: StackFit.expand,
                                alignment: Alignment.center,
                                overflow: Overflow.visible,
                                children: [
                                  ClipRRect(
                                    borderRadius: BorderRadius.zero,
                                    child: Container(
                                      color: Color.fromARGB(255, 255, 255, 255),
                                    ),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 0.0,
                                    right: null,
                                    bottom: null,
                                    width: 375.0,
                                    height: 812.0,
                                    child: GeneratedRectangle1Widget8(),
                                  ),
                                  Positioned(
                                    left: 293.0,
                                    top: 422.0,
                                    right: null,
                                    bottom: null,
                                    width: 12.0,
                                    height: 12.0,
                                    child: GeneratedBxsmusicWidget7(),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: -155.0,
                                    right: null,
                                    bottom: null,
                                    width: 375.0,
                                    height: 483.0,
                                    child: GeneratedUnsplash0EEKgGOe3psWidget(),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: -155.0,
                                    right: null,
                                    bottom: null,
                                    width: 375.0,
                                    height: 483.0,
                                    child:
                                        GeneratedUnsplash0EEKgGOe3psWidget1(),
                                  ),
                                  Positioned(
                                    left: 14.0,
                                    top: 371.0,
                                    right: null,
                                    bottom: null,
                                    width: 307.0,
                                    height: 146.0,
                                    child: GeneratedHiphopPopulerWidget1(),
                                  ),
                                  Positioned(
                                    left: 40.0,
                                    top: 260.0,
                                    right: null,
                                    bottom: null,
                                    width: 298.0,
                                    height: 30.0,
                                    child: GeneratedHiphopPopulerWidget2(),
                                  ),
                                  Positioned(
                                    left: 35.0,
                                    top: 349.0,
                                    right: null,
                                    bottom: null,
                                    width: 305.0,
                                    height: 85.0,
                                    child: GeneratedFrame9Widget(),
                                  ),
                                  Positioned(
                                    left: 35.0,
                                    top: 456.0,
                                    right: null,
                                    bottom: null,
                                    width: 305.0,
                                    height: 85.0,
                                    child: GeneratedFrame10Widget(),
                                  ),
                                  Positioned(
                                    left: 35.0,
                                    top: 563.0,
                                    right: null,
                                    bottom: null,
                                    width: 305.0,
                                    height: 85.0,
                                    child: GeneratedFrame11Widget(),
                                  ),
                                  Positioned(
                                    left: 35.0,
                                    top: 670.0,
                                    right: null,
                                    bottom: null,
                                    width: 305.0,
                                    height: 85.0,
                                    child: GeneratedFrame14Widget(),
                                  ),
                                  Positioned(
                                    left: 35.0,
                                    top: 777.0,
                                    right: null,
                                    bottom: null,
                                    width: 305.0,
                                    height: 85.0,
                                    child: GeneratedFrame15Widget(),
                                  ),
                                  Positioned(
                                    left: 35.0,
                                    top: 884.0,
                                    right: null,
                                    bottom: null,
                                    width: 305.0,
                                    height: 85.0,
                                    child: GeneratedFrame16Widget(),
                                  ),
                                  Positioned(
                                    left: 442.0,
                                    top: 232.0,
                                    right: null,
                                    bottom: null,
                                    width: 112.0,
                                    height: 112.0,
                                    child: GeneratedRectangle12Widget(),
                                  ),
                                  Positioned(
                                    left: 442.0,
                                    top: 352.0,
                                    right: null,
                                    bottom: null,
                                    width: 114.0,
                                    height: 21.0,
                                    child: GeneratedWantItAllfeWidget(),
                                  ),
                                  Positioned(
                                    left: 442.0,
                                    top: 371.0,
                                    right: null,
                                    bottom: null,
                                    width: 114.0,
                                    height: 21.0,
                                    child: GeneratedBurnaBoyWidget(),
                                  ),
                                  Positioned(
                                    left: 442.0,
                                    top: 232.0,
                                    right: null,
                                    bottom: null,
                                    width: 112.0,
                                    height: 112.63636016845703,
                                    child: GeneratedImage10Widget(),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 0.0,
                                    right: 0.0,
                                    bottom: 0.0,
                                    width: null,
                                    height: null,
                                    child: LayoutBuilder(builder:
                                        (BuildContext context,
                                            BoxConstraints constraints) {
                                      final double width =
                                          constraints.maxWidth * 0.072;

                                      final double height =
                                          constraints.maxHeight *
                                              0.02509293680297398;

                                      return Stack(children: [
                                        TransformHelper.translate(
                                            x: constraints.maxWidth *
                                                0.06933333333333333,
                                            y: constraints.maxHeight *
                                                0.055762081784386616,
                                            z: 0,
                                            child: Container(
                                              width: width,
                                              height: height,
                                              child:
                                                  GeneratedEvaarrowiosbackoutlineWidget4(),
                                            ))
                                      ]);
                                    }),
                                  )
                                ]),
                          ))
                    ])),
              );
            }),
            Positioned(
              left: null,
              top: null,
              right: 35.0,
              bottom: 30.0,
              width: 305.0,
              height: 66.0,
              child: GeneratedFrame13Widget(),
            )
          ]),
    ));
  }
}
