import 'package:flutter/material.dart';

/* Rectangle image 3
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedImage3Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 1002.0,
      height: 870.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Image.asset(
          "assets/images/3db49936f43d0399944a2e86a138edbf2f06200c.png",
          color: null,
          fit: BoxFit.cover,
          width: 1002.0,
          height: 870.0,
          colorBlendMode: BlendMode.dstATop,
        ),
      ),
    ));
  }
}
