import 'package:flutter/material.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedloginwidget/generated/GeneratedBxlockaltWidget.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedloginwidget/generated/GeneratedAkariconseyeslashedWidget.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedloginwidget/generated/GeneratedGroup1Widget1.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedloginwidget/generated/GeneratedGroup7Widget.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedloginwidget/generated/GeneratedGroup3Widget.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedloginwidget/generated/GeneratedBxsmusicWidget4.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedloginwidget/generated/GeneratedPasswordWidget.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedloginwidget/generated/GeneratedLine2Widget.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedloginwidget/generated/GeneratedCimailWidget.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedloginwidget/generated/GeneratedGroup4Widget.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedloginwidget/generated/GeneratedLine1Widget.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedloginwidget/generated/GeneratedEmailIDWidget.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedloginwidget/generated/GeneratedRectangle1Widget2.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedloginwidget/generated/GeneratedMasukWidget.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedloginwidget/generated/GeneratedSignIn1Widget.dart';

/* Frame Login
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLoginWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 812.0,
                child: GeneratedRectangle1Widget2(),
              ),
              Positioned(
                left: 318.0,
                top: 259.0,
                right: null,
                bottom: null,
                width: 12.0,
                height: 12.0,
                child: GeneratedBxsmusicWidget4(),
              ),
              Positioned(
                left: 33.0,
                top: 372.0,
                right: null,
                bottom: null,
                width: 310.0,
                height: 51.0,
                child: GeneratedMasukWidget(),
              ),
              Positioned(
                left: 33.0,
                top: 432.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedCimailWidget(),
              ),
              Positioned(
                left: 78.0,
                top: 452.0,
                right: null,
                bottom: null,
                width: 262.0,
                height: 0.5,
                child: GeneratedLine1Widget(),
              ),
              Positioned(
                left: 78.0,
                top: 430.0,
                right: null,
                bottom: null,
                width: 128.0,
                height: 20.0,
                child: GeneratedEmailIDWidget(),
              ),
              Positioned(
                left: 33.0,
                top: 494.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedBxlockaltWidget(),
              ),
              Positioned(
                left: 78.0,
                top: 516.0,
                right: null,
                bottom: null,
                width: 262.0,
                height: 0.5,
                child: GeneratedLine2Widget(),
              ),
              Positioned(
                left: 79.0,
                top: 494.0,
                right: null,
                bottom: null,
                width: 131.0,
                height: 23.0,
                child: GeneratedPasswordWidget(),
              ),
              Positioned(
                left: 35.0,
                top: 633.0,
                right: null,
                bottom: null,
                width: 305.0,
                height: 18.0,
                child: GeneratedGroup3Widget(),
              ),
              Positioned(
                left: 317.0,
                top: 488.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedAkariconseyeslashedWidget(),
              ),
              Positioned(
                left: 36.0,
                top: 569.0,
                right: null,
                bottom: null,
                width: 305.0,
                height: 35.0,
                child: GeneratedGroup1Widget1(),
              ),
              Positioned(
                left: 36.0,
                top: 677.0,
                right: null,
                bottom: null,
                width: 305.0,
                height: 35.0,
                child: GeneratedGroup4Widget(),
              ),
              Positioned(
                left: -22.0,
                top: 44.0,
                right: null,
                bottom: null,
                width: 409.0,
                height: 308.0,
                child: GeneratedSignIn1Widget(),
              ),
              Positioned(
                left: 103.0,
                top: 731.0,
                right: null,
                bottom: null,
                width: 162.0,
                height: 19.0,
                child: GeneratedGroup7Widget(),
              )
            ]),
      ),
    ));
  }
}
