import 'package:flutter/material.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedhomewidget/generated/GeneratedTemukanmusikfavoritmuhariiniWidget.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedhomewidget/generated/GeneratedRekomendasiWidget.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedhomewidget/generated/GeneratedAkariconssearchWidget.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedhomewidget/generated/GeneratedFrame24Widget.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedhomewidget/generated/GeneratedBxsmusicWidget5.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedhomewidget/generated/GeneratedFrame4Widget.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedhomewidget/generated/GeneratedFrame22Widget.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedhomewidget/generated/GeneratedRekomendasiWidget1.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedhomewidget/generated/GeneratedFrame26Widget.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedhomewidget/generated/GeneratedFrame23Widget.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedhomewidget/generated/GeneratedGroup4Widget1.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedhomewidget/generated/GeneratedFrame25Widget.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedhomewidget/generated/GeneratedAntdesignsettingoutlinedWidget.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedhomewidget/generated/GeneratedRectangle1Widget5.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedhomewidget/generated/GeneratedGroup38Widget.dart';

/* Frame Home
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHomeWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              return SingleChildScrollView(
                scrollDirection: Axis.vertical,
                child: Container(
                    height: 1076.0,
                    child: Stack(children: [
                      Container(
                          width: constraints.maxWidth,
                          child: Container(
                            width: 375.0,
                            height: 1076.0,
                            child: Stack(
                                fit: StackFit.expand,
                                alignment: Alignment.center,
                                overflow: Overflow.visible,
                                children: [
                                  ClipRRect(
                                    borderRadius: BorderRadius.zero,
                                    child: Container(
                                      color: Color.fromARGB(255, 255, 255, 255),
                                    ),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 0.0,
                                    right: null,
                                    bottom: null,
                                    width: 375.0,
                                    height: 812.0,
                                    child: GeneratedRectangle1Widget5(),
                                  ),
                                  Positioned(
                                    left: 318.0,
                                    top: 259.0,
                                    right: null,
                                    bottom: null,
                                    width: 12.0,
                                    height: 12.0,
                                    child: GeneratedBxsmusicWidget5(),
                                  ),
                                  Positioned(
                                    left: 35.0,
                                    top: 67.0,
                                    right: null,
                                    bottom: null,
                                    width: 146.0,
                                    height: 37.0,
                                    child: GeneratedGroup38Widget(),
                                  ),
                                  Positioned(
                                    left: 34.0,
                                    top: 138.0,
                                    right: null,
                                    bottom: null,
                                    width: 254.0,
                                    height: 82.0,
                                    child:
                                        GeneratedTemukanmusikfavoritmuhariiniWidget(),
                                  ),
                                  Positioned(
                                    left: 313.0,
                                    top: 104.0,
                                    right: null,
                                    bottom: null,
                                    width: 30.0,
                                    height: 30.0,
                                    child:
                                        GeneratedAntdesignsettingoutlinedWidget(),
                                  ),
                                  Positioned(
                                    left: null,
                                    top: 229.0,
                                    right: null,
                                    bottom: null,
                                    width: 305.0,
                                    height: 43.0,
                                    child: GeneratedGroup4Widget1(),
                                  ),
                                  Positioned(
                                    left: 49.0,
                                    top: 240.0,
                                    right: null,
                                    bottom: null,
                                    width: 24.0,
                                    height: 24.0,
                                    child: GeneratedAkariconssearchWidget(),
                                  ),
                                  Positioned(
                                    left: 34.0,
                                    top: 299.0,
                                    right: null,
                                    bottom: null,
                                    width: 310.0,
                                    height: 28.0,
                                    child: GeneratedFrame24Widget(),
                                  ),
                                  Positioned(
                                    left: 34.0,
                                    top: 497.0,
                                    right: null,
                                    bottom: null,
                                    width: 310.0,
                                    height: 28.0,
                                    child: GeneratedFrame25Widget(),
                                  ),
                                  Positioned(
                                    left: 34.0,
                                    top: 696.0,
                                    right: null,
                                    bottom: null,
                                    width: 310.0,
                                    height: 28.0,
                                    child: GeneratedFrame23Widget(),
                                  ),
                                  Positioned(
                                    left: 35.0,
                                    top: 346.0,
                                    right: null,
                                    bottom: null,
                                    width: 340.0,
                                    height: 112.0,
                                    child: GeneratedRekomendasiWidget(),
                                  ),
                                  Positioned(
                                    left: 35.0,
                                    top: 544.0,
                                    right: null,
                                    bottom: null,
                                    width: 340.0,
                                    height: 112.0,
                                    child: GeneratedRekomendasiWidget1(),
                                  ),
                                  Positioned(
                                    left: 34.0,
                                    top: 544.0,
                                    right: null,
                                    bottom: null,
                                    width: 341.0,
                                    height: 112.0,
                                    child: GeneratedFrame26Widget(),
                                  ),
                                  Positioned(
                                    left: 35.0,
                                    top: 744.0,
                                    right: null,
                                    bottom: null,
                                    width: 340.0,
                                    height: 120.0,
                                    child: GeneratedFrame4Widget(),
                                  )
                                ]),
                          ))
                    ])),
              );
            }),
            Positioned(
              left: null,
              top: null,
              right: null,
              bottom: 26.0,
              width: 305.0,
              height: 66.0,
              child: GeneratedFrame22Widget(),
            )
          ]),
    ));
  }
}
