import 'package:flutter/material.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedfirsttimepagewidget/generated/GeneratedTemukangenremusiksesuaidenganseleramuWidget.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedfirsttimepagewidget/generated/GeneratedRectangle1Widget.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedfirsttimepagewidget/generated/GeneratedSelamatDatangWidget.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedfirsttimepagewidget/generated/GeneratedBxsmusicWidget3.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedfirsttimepagewidget/generated/GeneratedEllipse9Widget.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedfirsttimepagewidget/generated/GeneratedGroup1Widget.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedfirsttimepagewidget/generated/GeneratedGroup6Widget.dart';

/* Frame FIrst Time Page
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFIrstTimePageWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 812.0,
                child: GeneratedRectangle1Widget(),
              ),
              Positioned(
                left: -91.0,
                top: -10.0,
                right: null,
                bottom: null,
                width: 524.5767211914062,
                height: 502.0,
                child: GeneratedGroup6Widget(),
              ),
              Positioned(
                left: -374.0,
                top: 385.0,
                right: null,
                bottom: null,
                width: 808.0,
                height: 846.0,
                child: GeneratedEllipse9Widget(),
              ),
              Positioned(
                left: 35.0,
                top: 677.0,
                right: null,
                bottom: null,
                width: 142.0,
                height: 35.0,
                child: GeneratedGroup1Widget(),
              ),
              Positioned(
                left: 35.0,
                top: 586.0,
                right: null,
                bottom: null,
                width: 226.0,
                height: 48.0,
                child: GeneratedTemukangenremusiksesuaidenganseleramuWidget(),
              ),
              Positioned(
                left: 35.0,
                top: 492.0,
                right: null,
                bottom: null,
                width: 310.0,
                height: 129.0,
                child: GeneratedSelamatDatangWidget(),
              ),
              Positioned(
                left: 318.0,
                top: 239.0,
                right: null,
                bottom: null,
                width: 12.0,
                height: 12.0,
                child: GeneratedBxsmusicWidget3(),
              )
            ]),
      ),
    ));
  }
}
