import 'package:flutter/material.dart';

/* Rectangle image 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedImage1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 506.0,
      height: 364.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Image.asset(
          "assets/images/b9d8ec77f591d591235eccf9ce92e0e64e8dcdd6.png",
          color: null,
          fit: BoxFit.cover,
          width: 506.0,
          height: 364.0,
          colorBlendMode: BlendMode.dstATop,
        ),
      ),
    ));
  }
}
