import 'package:flutter/material.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedmusicpagewidget/generated/GeneratedGroup53Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedmusicpagewidget/generated/GeneratedXOTourLlif3Widget.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedmusicpagewidget/generated/GeneratedVideoWidget.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedmusicpagewidget/generated/GeneratedFrame17Widget.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedmusicpagewidget/generated/GeneratedBxsmusicWidget6.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedmusicpagewidget/generated/GeneratedLilUziVertWidget.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedmusicpagewidget/generated/GeneratedImage15Widget.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedmusicpagewidget/generated/GeneratedRectangle17Widget.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedmusicpagewidget/generated/GeneratedRectangle1Widget7.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedmusicpagewidget/generated/GeneratedEvaarrowiosbackoutlineWidget3.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedmusicpagewidget/generated/GeneratedGroup52Widget.dart';

/* Frame Music Page
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMusicPageWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              return SingleChildScrollView(
                scrollDirection: Axis.vertical,
                child: Container(
                    height: 1076.0,
                    child: Stack(children: [
                      Container(
                          width: constraints.maxWidth,
                          child: Container(
                            width: 375.0,
                            height: 1076.0,
                            child: Stack(
                                fit: StackFit.expand,
                                alignment: Alignment.center,
                                overflow: Overflow.visible,
                                children: [
                                  ClipRRect(
                                    borderRadius: BorderRadius.zero,
                                    child: Container(
                                      color: Color.fromARGB(255, 255, 255, 255),
                                    ),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 0.0,
                                    right: null,
                                    bottom: null,
                                    width: 375.0,
                                    height: 812.0,
                                    child: GeneratedRectangle1Widget7(),
                                  ),
                                  Positioned(
                                    left: 318.0,
                                    top: 259.0,
                                    right: null,
                                    bottom: null,
                                    width: 12.0,
                                    height: 12.0,
                                    child: GeneratedBxsmusicWidget6(),
                                  ),
                                  Positioned(
                                    left: -78.0,
                                    top: -6.0,
                                    right: null,
                                    bottom: null,
                                    width: 531.0,
                                    height: 526.0,
                                    child: GeneratedImage15Widget(),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 432.0,
                                    right: null,
                                    bottom: null,
                                    width: 375.0,
                                    height: 644.0,
                                    child: GeneratedRectangle17Widget(),
                                  ),
                                  Positioned(
                                    left: 35.0,
                                    top: 483.0,
                                    right: null,
                                    bottom: null,
                                    width: 250.0,
                                    height: 66.0,
                                    child: GeneratedXOTourLlif3Widget(),
                                  ),
                                  Positioned(
                                    left: 35.0,
                                    top: 528.0,
                                    right: null,
                                    bottom: null,
                                    width: 250.0,
                                    height: 42.0,
                                    child: GeneratedLilUziVertWidget(),
                                  ),
                                  Positioned(
                                    left: 35.0,
                                    top: 664.0,
                                    right: null,
                                    bottom: null,
                                    width: 253.0,
                                    height: 45.0,
                                    child: GeneratedVideoWidget(),
                                  ),
                                  Positioned(
                                    left: 35.0,
                                    top: 589.0,
                                    right: null,
                                    bottom: null,
                                    width: 222.0,
                                    height: 53.0,
                                    child: GeneratedGroup52Widget(),
                                  ),
                                  Positioned(
                                    left: 38.0,
                                    top: 712.0,
                                    right: null,
                                    bottom: null,
                                    width: 304.0,
                                    height: 190.0,
                                    child: GeneratedGroup53Widget(),
                                  )
                                ]),
                          ))
                    ])),
              );
            }),
            Positioned(
              left: null,
              top: 60.0,
              right: null,
              bottom: null,
              width: 27.0,
              height: 27.0,
              child: TransformHelper.translate(
                  x: -147.00,
                  y: 0.00,
                  z: 0,
                  child: GeneratedEvaarrowiosbackoutlineWidget3()),
            ),
            Positioned(
              left: null,
              top: null,
              right: 31.0,
              bottom: 29.0,
              width: 305.0,
              height: 66.0,
              child: GeneratedFrame17Widget(),
            )
          ]),
    ));
  }
}
