import 'package:flutter/material.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedfirstloginpagewidget/generated/GeneratedGroup1Widget4.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedfirstloginpagewidget/generated/GeneratedGroup21Widget.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedfirstloginpagewidget/generated/GeneratedGroup17Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedfirstloginpagewidget/generated/GeneratedRectangle1Widget22.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedfirstloginpagewidget/generated/GeneratedGroup15Widget.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedfirstloginpagewidget/generated/GeneratedGroup16Widget.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedfirstloginpagewidget/generated/GeneratedGroup24Widget.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedfirstloginpagewidget/generated/GeneratedGroup18Widget.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedfirstloginpagewidget/generated/GeneratedEvaarrowiosbackoutlineWidget15.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedfirstloginpagewidget/generated/GeneratedGroup23Widget.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedfirstloginpagewidget/generated/GeneratedGroup25Widget.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedfirstloginpagewidget/generated/GeneratedGroup19Widget.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedfirstloginpagewidget/generated/GeneratedGroup22Widget.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedfirstloginpagewidget/generated/GeneratedGroup20Widget.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedfirstloginpagewidget/generated/GeneratedBxsmusicWidget11.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedfirstloginpagewidget/generated/GeneratedPilihGenreMusikFavoritmuWidget.dart';

/* Frame First login page
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFirstloginpageWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 812.0,
                child: GeneratedRectangle1Widget22(),
              ),
              Positioned(
                left: 318.0,
                top: 259.0,
                right: null,
                bottom: null,
                width: 12.0,
                height: 12.0,
                child: GeneratedBxsmusicWidget11(),
              ),
              Positioned(
                left: 33.0,
                top: 188.0,
                right: null,
                bottom: null,
                width: 307.0,
                height: 86.0,
                child: GeneratedPilihGenreMusikFavoritmuWidget(),
              ),
              Positioned(
                left: 35.0,
                top: 608.0,
                right: null,
                bottom: null,
                width: 305.0,
                height: 35.0,
                child: GeneratedGroup1Widget4(),
              ),
              Positioned(
                left: 35.0,
                top: 304.0,
                right: null,
                bottom: null,
                width: 87.0,
                height: 32.0,
                child: GeneratedGroup15Widget(),
              ),
              Positioned(
                left: 134.0,
                top: 304.0,
                right: null,
                bottom: null,
                width: 97.0,
                height: 32.0,
                child: GeneratedGroup16Widget(),
              ),
              Positioned(
                left: 253.0,
                top: 416.0,
                right: null,
                bottom: null,
                width: 87.0,
                height: 32.0,
                child: GeneratedGroup22Widget(),
              ),
              Positioned(
                left: 35.0,
                top: 360.0,
                right: null,
                bottom: null,
                width: 111.0,
                height: 32.0,
                child: GeneratedGroup18Widget(),
              ),
              Positioned(
                left: 35.0,
                top: 416.0,
                right: null,
                bottom: null,
                width: 113.0,
                height: 32.0,
                child: GeneratedGroup20Widget(),
              ),
              Positioned(
                left: 156.0,
                top: 416.0,
                right: null,
                bottom: null,
                width: 87.0,
                height: 32.0,
                child: GeneratedGroup21Widget(),
              ),
              Positioned(
                left: 160.0,
                top: 360.0,
                right: null,
                bottom: null,
                width: 136.0,
                height: 32.0,
                child: GeneratedGroup19Widget(),
              ),
              Positioned(
                left: 35.0,
                top: 472.0,
                right: null,
                bottom: null,
                width: 125.0,
                height: 32.0,
                child: GeneratedGroup23Widget(),
              ),
              Positioned(
                left: 35.0,
                top: 528.0,
                right: null,
                bottom: null,
                width: 153.0,
                height: 32.0,
                child: GeneratedGroup25Widget(),
              ),
              Positioned(
                left: 172.0,
                top: 472.0,
                right: null,
                bottom: null,
                width: 125.0,
                height: 32.0,
                child: GeneratedGroup24Widget(),
              ),
              Positioned(
                left: 243.0,
                top: 304.0,
                right: null,
                bottom: null,
                width: 97.0,
                height: 32.0,
                child: GeneratedGroup17Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.072;

                  final double height =
                      constraints.maxHeight * 0.0332512315270936;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.06933333333333333,
                        y: constraints.maxHeight * 0.07266009852216748,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedEvaarrowiosbackoutlineWidget15(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
