import 'package:flutter/material.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedprofilewidget/generated/Generated9Widget.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedprofilewidget/generated/GeneratedGroup27Widget.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedprofilewidget/generated/GeneratedArthurWidget.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedprofilewidget/generated/GeneratedEditProfilWidget.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedprofilewidget/generated/GeneratedGenrefavoritWidget.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedprofilewidget/generated/GeneratedProfilWidget.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedprofilewidget/generated/GeneratedArthurgmailcomWidget.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedprofilewidget/generated/GeneratedClarityeditlineWidget.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedprofilewidget/generated/GeneratedRiwayatDeteksiWidget.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedprofilewidget/generated/GeneratedGroup28Widget.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedprofilewidget/generated/GeneratedEvaarrowiosbackoutlineWidget6.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedprofilewidget/generated/GeneratedDeteksiWidget.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedprofilewidget/generated/Generated2Widget.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedprofilewidget/generated/GeneratedVectorWidget260.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedprofilewidget/generated/GeneratedKeluarAkunWidget.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedprofilewidget/generated/GeneratedGroup4Widget2.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedprofilewidget/generated/GeneratedGroup26Widget4.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedprofilewidget/generated/GeneratedEvaarrowiosbackoutlineWidget7.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedprofilewidget/generated/GeneratedRectangle1Widget10.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedprofilewidget/generated/GeneratedUnsplashd1UPkiFd04AWidget1.dart';

/* Frame Profile
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedProfileWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 812.0,
                child: GeneratedRectangle1Widget10(),
              ),
              Positioned(
                left: 35.0,
                top: 704.0,
                right: null,
                bottom: null,
                width: 305.0,
                height: 66.0,
                child: GeneratedGroup26Widget4(),
              ),
              Positioned(
                left: 138.0,
                top: 120.0,
                right: null,
                bottom: null,
                width: 100.0,
                height: 100.0,
                child: GeneratedUnsplashd1UPkiFd04AWidget1(),
              ),
              Positioned(
                left: 40.0,
                top: 239.0,
                right: null,
                bottom: null,
                width: 301.0,
                height: 33.0,
                child: GeneratedArthurWidget(),
              ),
              Positioned(
                left: 40.0,
                top: 60.0,
                right: null,
                bottom: null,
                width: 301.0,
                height: 33.0,
                child: GeneratedProfilWidget(),
              ),
              Positioned(
                left: 40.0,
                top: 276.0,
                right: null,
                bottom: null,
                width: 301.0,
                height: 33.0,
                child: GeneratedArthurgmailcomWidget(),
              ),
              Positioned(
                left: 53.0,
                top: 328.0,
                right: null,
                bottom: null,
                width: 94.66666412353516,
                height: 32.0,
                child: Generated9Widget(),
              ),
              Positioned(
                left: 53.0,
                top: 361.0,
                right: null,
                bottom: null,
                width: 94.66666412353516,
                height: 32.0,
                child: GeneratedDeteksiWidget(),
              ),
              Positioned(
                left: 232.333251953125,
                top: 328.0,
                right: null,
                bottom: null,
                width: 94.66666412353516,
                height: 32.0,
                child: Generated2Widget(),
              ),
              Positioned(
                left: 201.0,
                top: 361.0,
                right: null,
                bottom: null,
                width: 157.0,
                height: 46.0,
                child: GeneratedGenrefavoritWidget(),
              ),
              Positioned(
                left: null,
                top: 424.0,
                right: null,
                bottom: null,
                width: 305.0,
                height: 40.0,
                child: TransformHelper.translate(
                    x: -1.00, y: 0.00, z: 0, child: GeneratedGroup4Widget2()),
              ),
              Positioned(
                left: null,
                top: 480.0,
                right: null,
                bottom: null,
                width: 305.0,
                height: 40.0,
                child: TransformHelper.translate(
                    x: -1.00, y: 0.00, z: 0, child: GeneratedGroup27Widget()),
              ),
              Positioned(
                left: null,
                top: 589.0,
                right: null,
                bottom: null,
                width: 305.0,
                height: 40.0,
                child: TransformHelper.translate(
                    x: -1.00, y: 0.00, z: 0, child: GeneratedGroup28Widget()),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.05333333333333334;

                  final double height =
                      constraints.maxHeight * 0.024630541871921183;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.856,
                        y: constraints.maxHeight * 0.5603448275862069,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedEvaarrowiosbackoutlineWidget6(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.05333333333333334;

                  final double height =
                      constraints.maxHeight * 0.024630541871921183;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.856,
                        y: constraints.maxHeight * 0.6280788177339901,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedEvaarrowiosbackoutlineWidget7(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 94.0,
                top: 435.0,
                right: null,
                bottom: null,
                width: 158.0,
                height: 29.0,
                child: GeneratedRiwayatDeteksiWidget(),
              ),
              Positioned(
                left: 94.0,
                top: 490.0,
                right: null,
                bottom: null,
                width: 158.0,
                height: 29.0,
                child: GeneratedEditProfilWidget(),
              ),
              Positioned(
                left: 110.0,
                top: 600.0,
                right: null,
                bottom: null,
                width: 158.0,
                height: 29.0,
                child: GeneratedKeluarAkunWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.05333333333333334;
                  double scaleX = (constraints.maxWidth * percentWidth) / 20.0;

                  double percentHeight = 0.025577869321325143;
                  double scaleY = (constraints.maxHeight * percentHeight) /
                      20.769229888916016;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.14133333333333334,
                        translateY: constraints.maxHeight * 0.5357142857142857,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget260())
                  ]);
                }),
              ),
              Positioned(
                left: 53.0,
                top: 488.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedClarityeditlineWidget(),
              )
            ]),
      ),
    ));
  }
}
