import 'package:flutter/material.dart';
import 'package:flutterapp/deteksi_20musikapp/generateddetectionpagewidget/generated/GeneratedFxemojicancellationxWidget.dart';
import 'package:flutterapp/deteksi_20musikapp/generateddetectionpagewidget/generated/GeneratedGroup31Widget5.dart';
import 'package:flutterapp/deteksi_20musikapp/generateddetectionpagewidget/generated/GeneratedMendeteksimusikWidget.dart';
import 'package:flutterapp/deteksi_20musikapp/generateddetectionpagewidget/generated/GeneratedMohonTungguWidget.dart';
import 'package:flutterapp/deteksi_20musikapp/generateddetectionpagewidget/generated/GeneratedBiarkankamimendeteksimusikinisejenakWidget.dart';
import 'package:flutterapp/deteksi_20musikapp/generateddetectionpagewidget/generated/GeneratedRectangle1Widget16.dart';

/* Frame Detection  Page
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDetectionPageWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 812.0,
                child: GeneratedRectangle1Widget16(),
              ),
              Positioned(
                left: 62.0,
                top: 144.0,
                right: null,
                bottom: null,
                width: 254.0,
                height: 34.0,
                child: GeneratedMohonTungguWidget(),
              ),
              Positioned(
                left: 40.0,
                top: 184.0,
                right: null,
                bottom: null,
                width: 298.0,
                height: 30.0,
                child: GeneratedBiarkankamimendeteksimusikinisejenakWidget(),
              ),
              Positioned(
                left: 40.0,
                top: 560.0,
                right: null,
                bottom: null,
                width: 298.0,
                height: 30.0,
                child: GeneratedMendeteksimusikWidget(),
              ),
              Positioned(
                left: 59.0,
                top: 256.0,
                right: null,
                bottom: null,
                width: 258.0,
                height: 304.0,
                child: GeneratedGroup31Widget5(),
              ),
              Positioned(
                left: 178.0,
                top: 712.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedFxemojicancellationxWidget(),
              )
            ]),
      ),
    ));
  }
}
