import 'package:flutter/material.dart';
import 'package:flutterapp/deteksi_20musikapp/generateddetectionpagewidget1/generated/GeneratedVectorWidget281.dart';
import 'package:flutterapp/deteksi_20musikapp/generateddetectionpagewidget1/generated/GeneratedGroup31Widget6.dart';
import 'package:flutterapp/deteksi_20musikapp/generateddetectionpagewidget1/generated/GeneratedSelesaiWidget.dart';
import 'package:flutterapp/deteksi_20musikapp/generateddetectionpagewidget1/generated/GeneratedGenremusikmuadalahWidget.dart';
import 'package:flutterapp/deteksi_20musikapp/generateddetectionpagewidget1/generated/GeneratedRectangle1Widget17.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/deteksi_20musikapp/generateddetectionpagewidget1/generated/GeneratedVectorWidget280.dart';
import 'package:flutterapp/deteksi_20musikapp/generateddetectionpagewidget1/generated/GeneratedRiwayatDeteksiWidget3.dart';
import 'package:flutterapp/deteksi_20musikapp/generateddetectionpagewidget1/generated/GeneratedHiphopWidget7.dart';
import 'package:flutterapp/deteksi_20musikapp/generateddetectionpagewidget1/generated/GeneratedGroup32Widget.dart';

/* Frame Detection  Page
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDetectionPageWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 812.0,
                child: GeneratedRectangle1Widget17(),
              ),
              Positioned(
                left: 62.0,
                top: 118.0,
                right: null,
                bottom: null,
                width: 257.0,
                height: 37.0,
                child: GeneratedSelesaiWidget(),
              ),
              Positioned(
                left: 72.5789794921875,
                top: 184.0,
                right: null,
                bottom: null,
                width: 230.84210205078125,
                height: 272.0,
                child: GeneratedGroup31Widget6(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.08;
                  double scaleX = (constraints.maxWidth * percentWidth) / 30.0;

                  double percentHeight = 0.027093596059113302;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 22.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.4613333333333333,
                        translateY: constraints.maxHeight * 0.5480295566502463,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget280())
                  ]);
                }),
              ),
              Positioned(
                left: 40.0,
                top: 480.0,
                right: null,
                bottom: null,
                width: 298.0,
                height: 30.0,
                child: GeneratedGenremusikmuadalahWidget(),
              ),
              Positioned(
                left: 40.0,
                top: 657.0,
                right: null,
                bottom: null,
                width: 298.0,
                height: 30.0,
                child: GeneratedRiwayatDeteksiWidget3(),
              ),
              Positioned(
                left: 40.0,
                top: 512.0,
                right: null,
                bottom: null,
                width: 301.0,
                height: 53.0,
                child: GeneratedHiphopWidget7(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.06089557902018229;
                  double scaleX =
                      (constraints.maxWidth * percentWidth) / 22.83584213256836;

                  double percentHeight = 0.030789398794690965;
                  double scaleY = (constraints.maxHeight * percentHeight) /
                      25.000991821289062;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.472,
                        translateY: constraints.maxHeight * 0.8854679802955665,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget281())
                  ]);
                }),
              ),
              Positioned(
                left: 67.0,
                top: 630.0,
                right: null,
                bottom: null,
                width: 242.0,
                height: 23.0,
                child: GeneratedGroup32Widget(),
              )
            ]),
      ),
    ));
  }
}
