import 'package:flutter/material.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedpagerekomendasiwidget/generated/GeneratedHiphopTerbaruCardWidget.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedpagerekomendasiwidget/generated/GeneratedFrame5Widget.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedpagerekomendasiwidget/generated/GeneratedGroup30Widget4.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedpagerekomendasiwidget/generated/GeneratedFrame4Widget1.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedpagerekomendasiwidget/generated/GeneratedArtisCardWidget.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedpagerekomendasiwidget/generated/GeneratedRekomendasiHiphopWidget1.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedpagerekomendasiwidget/generated/GeneratedFrame8Widget.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedpagerekomendasiwidget/generated/GeneratedHiphopPopulerHeadWidget.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedpagerekomendasiwidget/generated/GeneratedFrame7Widget1.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedpagerekomendasiwidget/generated/GeneratedRectangle1Widget15.dart';
import 'package:flutterapp/deteksi_20musikapp/generatedpagerekomendasiwidget/generated/GeneratedHiphopPopulerCardWidget.dart';

/* Frame Page rekomendasi
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPagerekomendasiWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              return SingleChildScrollView(
                scrollDirection: Axis.vertical,
                child: Container(
                    height: 1076.0,
                    child: Stack(children: [
                      Container(
                          width: constraints.maxWidth,
                          child: Container(
                            width: 375.0,
                            height: 1076.0,
                            child: Stack(
                                fit: StackFit.expand,
                                alignment: Alignment.center,
                                overflow: Overflow.visible,
                                children: [
                                  ClipRRect(
                                    borderRadius: BorderRadius.zero,
                                    child: Container(
                                      color: Color.fromARGB(255, 255, 255, 255),
                                    ),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 0.0,
                                    right: null,
                                    bottom: null,
                                    width: 375.0,
                                    height: 812.0,
                                    child: GeneratedRectangle1Widget15(),
                                  ),
                                  Positioned(
                                    left: 40.0,
                                    top: 60.0,
                                    right: null,
                                    bottom: null,
                                    width: 298.0,
                                    height: 30.0,
                                    child: GeneratedRekomendasiHiphopWidget1(),
                                  ),
                                  Positioned(
                                    left: 34.0,
                                    top: 114.0,
                                    right: null,
                                    bottom: null,
                                    width: 310.0,
                                    height: 28.0,
                                    child: GeneratedHiphopPopulerHeadWidget(),
                                  ),
                                  Positioned(
                                    left: 35.0,
                                    top: 160.0,
                                    right: null,
                                    bottom: null,
                                    width: 340.0,
                                    height: 158.0,
                                    child: GeneratedHiphopPopulerCardWidget(),
                                  ),
                                  Positioned(
                                    left: 35.0,
                                    top: 344.0,
                                    right: null,
                                    bottom: null,
                                    width: 310.0,
                                    height: 28.0,
                                    child: GeneratedFrame7Widget1(),
                                  ),
                                  Positioned(
                                    left: 35.0,
                                    top: 584.0,
                                    right: null,
                                    bottom: null,
                                    width: 310.0,
                                    height: 28.0,
                                    child: GeneratedFrame8Widget(),
                                  ),
                                  Positioned(
                                    left: 35.0,
                                    top: 636.0,
                                    right: null,
                                    bottom: null,
                                    width: 340.0,
                                    height: 103.0,
                                    child: GeneratedArtisCardWidget(),
                                  ),
                                  Positioned(
                                    left: 35.0,
                                    top: 398.0,
                                    right: null,
                                    bottom: null,
                                    width: 340.0,
                                    height: 154.0,
                                    child: GeneratedHiphopTerbaruCardWidget(),
                                  ),
                                  Positioned(
                                    left: 34.0,
                                    top: 763.0,
                                    right: null,
                                    bottom: null,
                                    width: 310.0,
                                    height: 28.0,
                                    child: GeneratedGroup30Widget4(),
                                  ),
                                  Positioned(
                                    left: 35.0,
                                    top: 811.0,
                                    right: null,
                                    bottom: null,
                                    width: 340.0,
                                    height: 120.0,
                                    child: GeneratedFrame4Widget1(),
                                  )
                                ]),
                          ))
                    ])),
              );
            }),
            Positioned(
              left: null,
              top: null,
              right: 35.0,
              bottom: 29.0,
              width: 305.0,
              height: 66.0,
              child: GeneratedFrame5Widget(),
            )
          ]),
    ));
  }
}
